-- ICD-10 diagnosis catalog (master reference)
CREATE TABLE "icd10_codes" (
    "code" VARCHAR(10) NOT NULL,
    "description" VARCHAR(300) NOT NULL,
    "category" VARCHAR(100),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT "icd10_codes_pkey" PRIMARY KEY ("code")
);

CREATE INDEX "icd10_codes_description_idx" ON "icd10_codes"("description");

-- Seed: common codes (subset; expand with a full ICD-10 import later)
INSERT INTO "icd10_codes" ("code", "description", "category") VALUES
('I10', 'Essential (primary) hypertension', 'Circulatory'),
('I20.0', 'Unstable angina', 'Circulatory'),
('I21.9', 'Acute myocardial infarction, unspecified', 'Circulatory'),
('I25.10', 'Atherosclerotic heart disease of native coronary artery', 'Circulatory'),
('I48.91', 'Unspecified atrial fibrillation', 'Circulatory'),
('I50.9', 'Heart failure, unspecified', 'Circulatory'),
('I63.9', 'Cerebral infarction, unspecified', 'Circulatory'),
('E11.9', 'Type 2 diabetes mellitus without complications', 'Endocrine'),
('E11.65', 'Type 2 diabetes mellitus with hyperglycemia', 'Endocrine'),
('E10.9', 'Type 1 diabetes mellitus without complications', 'Endocrine'),
('E78.5', 'Hyperlipidemia, unspecified', 'Endocrine'),
('E03.9', 'Hypothyroidism, unspecified', 'Endocrine'),
('E66.9', 'Obesity, unspecified', 'Endocrine'),
('J18.9', 'Pneumonia, unspecified organism', 'Respiratory'),
('J45.909', 'Unspecified asthma, uncomplicated', 'Respiratory'),
('J44.9', 'Chronic obstructive pulmonary disease, unspecified', 'Respiratory'),
('J20.9', 'Acute bronchitis, unspecified', 'Respiratory'),
('J06.9', 'Acute upper respiratory infection, unspecified', 'Respiratory'),
('J02.9', 'Acute pharyngitis, unspecified', 'Respiratory'),
('A09', 'Infectious gastroenteritis and colitis, unspecified', 'Infectious'),
('A90', 'Dengue fever', 'Infectious'),
('B50.9', 'Plasmodium falciparum malaria, unspecified', 'Infectious'),
('A15.0', 'Tuberculosis of lung', 'Infectious'),
('A01.0', 'Typhoid fever', 'Infectious'),
('B19.9', 'Unspecified viral hepatitis without hepatic coma', 'Infectious'),
('U07.1', 'COVID-19', 'Infectious'),
('K29.70', 'Gastritis, unspecified, without bleeding', 'Digestive'),
('K21.9', 'Gastro-esophageal reflux disease without esophagitis', 'Digestive'),
('K35.80', 'Unspecified acute appendicitis', 'Digestive'),
('K80.20', 'Calculus of gallbladder without cholecystitis', 'Digestive'),
('K59.00', 'Constipation, unspecified', 'Digestive'),
('B82.9', 'Intestinal parasitism, unspecified', 'Digestive'),
('N39.0', 'Urinary tract infection, site not specified', 'Genitourinary'),
('N18.9', 'Chronic kidney disease, unspecified', 'Genitourinary'),
('N20.0', 'Calculus of kidney', 'Genitourinary'),
('M54.5', 'Low back pain', 'Musculoskeletal'),
('M54.2', 'Cervicalgia', 'Musculoskeletal'),
('M25.50', 'Pain in unspecified joint', 'Musculoskeletal'),
('M79.1', 'Myalgia', 'Musculoskeletal'),
('M17.9', 'Osteoarthritis of knee, unspecified', 'Musculoskeletal'),
('R51.9', 'Headache, unspecified', 'Symptoms'),
('R50.9', 'Fever, unspecified', 'Symptoms'),
('R10.9', 'Unspecified abdominal pain', 'Symptoms'),
('R05.9', 'Cough, unspecified', 'Symptoms'),
('R07.9', 'Chest pain, unspecified', 'Symptoms'),
('R42', 'Dizziness and giddiness', 'Symptoms'),
('R11.2', 'Nausea with vomiting, unspecified', 'Symptoms'),
('R53.83', 'Other fatigue', 'Symptoms'),
('G43.909', 'Migraine, unspecified, not intractable', 'Nervous'),
('G40.909', 'Epilepsy, unspecified, not intractable', 'Nervous'),
('F32.9', 'Major depressive disorder, single episode, unspecified', 'Mental'),
('F41.9', 'Anxiety disorder, unspecified', 'Mental'),
('F41.1', 'Generalized anxiety disorder', 'Mental'),
('D64.9', 'Anemia, unspecified', 'Blood'),
('D50.9', 'Iron deficiency anemia, unspecified', 'Blood'),
('L23.9', 'Allergic contact dermatitis, unspecified cause', 'Skin'),
('L50.9', 'Urticaria, unspecified', 'Skin'),
('H10.9', 'Unspecified conjunctivitis', 'Eye'),
('H66.90', 'Otitis media, unspecified, unspecified ear', 'Ear'),
('O80', 'Encounter for full-term uncomplicated delivery', 'Pregnancy'),
('Z00.00', 'General adult medical examination without abnormal findings', 'Factors');
