export const LAB_TEST_SEEDS = [
  {
    code: 'HEMOGLOBIN',
    name: 'Hemoglobin',
    category: 'Hematology',
    sampleType: 'Blood',
    price: 5000,
    referenceRanges: [
      {
        gender: 'MALE',
        ageMin: 0,
        ageMax: 150,
        low: 13.5,
        high: 17.5,
        unit: 'g/dL',
        criticalLow: 7,
        criticalHigh: 20,
      },
      {
        gender: 'FEMALE',
        ageMin: 0,
        ageMax: 150,
        low: 12,
        high: 15.5,
        unit: 'g/dL',
        criticalLow: 7,
        criticalHigh: 20,
      },
    ],
  },
  {
    code: 'WBC',
    name: 'White Blood Cells',
    category: 'Hematology',
    sampleType: 'Blood',
    price: 5000,
    referenceRanges: [
      {
        gender: 'MALE',
        ageMin: 0,
        ageMax: 150,
        low: 4,
        high: 11,
        unit: '10³/µL',
        criticalLow: 1,
        criticalHigh: 30,
      },
      {
        gender: 'FEMALE',
        ageMin: 0,
        ageMax: 150,
        low: 4,
        high: 11,
        unit: '10³/µL',
        criticalLow: 1,
        criticalHigh: 30,
      },
    ],
  },
  {
    code: 'POTASSIUM',
    name: 'Potassium',
    category: 'Chemistry',
    sampleType: 'Blood',
    price: 8000,
    referenceRanges: [
      {
        gender: 'MALE',
        ageMin: 0,
        ageMax: 150,
        low: 3.5,
        high: 5.1,
        unit: 'mmol/L',
        criticalLow: 2.5,
        criticalHigh: 6.5,
      },
      {
        gender: 'FEMALE',
        ageMin: 0,
        ageMax: 150,
        low: 3.5,
        high: 5.1,
        unit: 'mmol/L',
        criticalLow: 2.5,
        criticalHigh: 6.5,
      },
    ],
  },
  {
    code: 'SODIUM',
    name: 'Sodium',
    category: 'Chemistry',
    sampleType: 'Blood',
    price: 8000,
    referenceRanges: [
      {
        gender: 'MALE',
        ageMin: 0,
        ageMax: 150,
        low: 135,
        high: 145,
        unit: 'mmol/L',
        criticalLow: 120,
        criticalHigh: 160,
      },
      {
        gender: 'FEMALE',
        ageMin: 0,
        ageMax: 150,
        low: 135,
        high: 145,
        unit: 'mmol/L',
        criticalLow: 120,
        criticalHigh: 160,
      },
    ],
  },
  {
    code: 'CBC',
    name: 'Complete Blood Count',
    category: 'Hematology',
    sampleType: 'Blood',
    price: 15000,
    referenceRanges: [
      {
        gender: 'MALE',
        ageMin: 0,
        ageMax: 150,
        low: 13.5,
        high: 17.5,
        unit: 'g/dL',
        criticalLow: 7,
        criticalHigh: 20,
      },
      {
        gender: 'FEMALE',
        ageMin: 0,
        ageMax: 150,
        low: 12,
        high: 15.5,
        unit: 'g/dL',
        criticalLow: 7,
        criticalHigh: 20,
      },
    ],
  },
  {
    code: 'LIPID',
    name: 'Lipid panel',
    category: 'Chemistry',
    sampleType: 'Blood',
    price: 35000,
    referenceRanges: [
      {
        gender: 'MALE',
        ageMin: 0,
        ageMax: 150,
        low: 100,
        high: 200,
        unit: 'mg/dL',
        criticalLow: 50,
        criticalHigh: 300,
      },
      {
        gender: 'FEMALE',
        ageMin: 0,
        ageMax: 150,
        low: 100,
        high: 200,
        unit: 'mg/dL',
        criticalLow: 50,
        criticalHigh: 300,
      },
    ],
  },
  {
    code: 'UA',
    name: 'Urinalysis',
    category: 'Microbiology',
    sampleType: 'Urine',
    price: 10000,
    referenceRanges: [
      {
        gender: 'MALE',
        ageMin: 0,
        ageMax: 150,
        low: 5,
        high: 8,
        unit: 'pH',
        criticalLow: 4.5,
        criticalHigh: 9,
      },
      {
        gender: 'FEMALE',
        ageMin: 0,
        ageMax: 150,
        low: 5,
        high: 8,
        unit: 'pH',
        criticalLow: 4.5,
        criticalHigh: 9,
      },
    ],
  },
] as const;
